# Generated by Django 5.2.6 on 2025-09-17 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highscores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='highscore',
            name='time',
            field=models.IntegerField(null=True),
        ),
    ]
